TEST_DIR: ./data/imagenet-c
VAL_DIR: ./data/imagenet/val
CALIBRATOR: 
  NAME: FixedTS
  TS: 1.109
  TL: 0.621
  CORRUPTIONS:
    - 'gaussian_blur'
    - 'saturate'
    - 'spatter'
    - 'speckle_noise'
  SEVERITIES: 
    - 1
    - 2
    - 3
    - 4
    - 5

LARGE: 
  NAME: vit_b_16
  BS: 128
  WORKERS: 8
  NORM: LN
  OPTIM:    
    # METHOD: "Adam"
    # STEPS: 1       # Tune this per model
    # LR: 3e-5     # Tune this per model
    # BETA: 0.9
    # WD: 0.0
    METHOD: "SGD"
    STEPS: 1       # Tune this per model
    LR: 0.0005     # Tune this per model
    MOMENTUM: 0.0
    WD: 0.0
    NESTEROV: false
    DAMPENING: 0.0

SMALL: 
  NAME: resnet50
  BS: 128
  WORKERS: 8
  NORM: BN
  OPTIM:    
    # METHOD: "Adam"
    # STEPS: 1       # Tune this per model
    # LR: 3e-5     # Tune this per model
    # BETA: 0.9
    # WD: 0.0
    METHOD: "SGD"
    STEPS: 1       # Tune this per model
    LR: 0.0005     # Tune this per model
    MOMENTUM: 0.0
    WD: 0.0
    NESTEROV: false
    DAMPENING: 0.0


