"""
tables.py
=========
LaTeX tables from tidy result rows. Replaces `write_accuracy_latex_table` of the old diagnostics code, with
three differences that matter for the paper:

  * columns are keyed by corruption NAME, never by position (the old Frozen rows came out in the canonical
    ImageNet-C order instead of the header order);
  * cells are mean +- std over seeds, with the "Avg." column the std of the PER-SEED averages (see
    src/experiments/results.py);
  * one generic `latex_table` for every other table (proxies, generality, continual, ablations).

Needs `booktabs`, `multirow` and `graphicx` in the document that \\input{}s the file. Values are fractions in
the data and percentages in the table; "--" marks a cell with no data.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Sequence

import numpy as np
import pandas as pd

_ESCAPES = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
            "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def latex_escape(s: str) -> str:
    return "".join(_ESCAPES.get(ch, ch) for ch in s)


# Hendrycks & Dietterich's column abbreviations; the family grouping itself comes from cfgs/global.yaml.
ABBREV = {
    "gaussian_noise": "Gauss.", "shot_noise": "Shot", "impulse_noise": "Impulse",
    "defocus_blur": "Defocus", "glass_blur": "Glass", "motion_blur": "Motion", "zoom_blur": "Zoom",
    "snow": "Snow", "frost": "Frost", "fog": "Fog", "brightness": "Bright.",
    "contrast": "Contrast", "elastic_transform": "Elastic", "pixelate": "Pixel.", "jpeg_compression": "JPEG",
    "gaussian_blur": "G.Blur", "saturate": "Saturate", "spatter": "Spatter", "speckle_noise": "Speckle",
    "imagenet_r": "IN-R", "imagenet_a": "IN-A", "imagenet_sketch": "Sketch", "imagenet_v2": "V2",
}


def fmt_cell(mean: float, std: float | None = None, decimals: int = 1, pct: bool = True) -> str:
    """'51.3' or '51.3 {\\scriptsize$\\pm$0.4}'; '--' for no data. A NaN std (one seed) prints no spread."""
    if mean is None or not math.isfinite(mean):
        return "--"
    k = 100.0 if pct else 1.0
    text = f"{k * mean:.{decimals}f}"
    if std is not None and math.isfinite(std):
        text += f" {{\\scriptsize$\\pm${k * std:.{decimals}f}}}"
    return text


def table_env(body: Sequence[str], col_spec: str, caption: str, label: str, *, star: bool = False,
              resize: bool = True, source: str = "") -> str:
    env = "table*" if star else "table"
    lines = [f"% Generated by {source or 'src/utils/tables.py'}. Requires booktabs, multirow, graphicx.",
             f"\\begin{{{env}}}[t]", "    \\centering", "    \\small",
             f"    \\caption{{{caption}}}", f"    \\label{{{label}}}"]
    if resize:
        lines.append("    \\resizebox{\\columnwidth}{!}{%" if not star else "    \\resizebox{\\textwidth}{!}{%")
    lines += [f"    \\begin{{tabular}}{{{col_spec}}}", "        \\toprule", *("        " + b for b in body),
              "        \\bottomrule", "    \\end{tabular}" + ("%" if resize else "")]
    if resize:
        lines.append("    }")
    lines.append(f"\\end{{{env}}}")
    return "\n".join(lines) + "\n"


def latex_table(header: Sequence[str], rows: Sequence[Sequence[str]], *, caption: str, label: str,
                col_spec: str | None = None, midrule_before: Sequence[int] = (), star: bool = False,
                resize: bool = True, source: str = "", escape_header: bool = True) -> str:
    """A plain table. `rows` are lists of already-formatted cells (use fmt_cell); a \\midrule goes before each
    row index in `midrule_before`. Header cells are escaped unless escape_header=False (for math)."""
    col_spec = col_spec or "l" + "c" * (len(header) - 1)
    head = [(latex_escape(h) if escape_header else h) for h in header]
    body = [" & ".join(head) + " \\\\", "\\midrule"]
    for i, r in enumerate(rows):
        if i in set(midrule_before):
            body.append("\\midrule")
        body.append(" & ".join(r) + " \\\\")
    return table_env(body, col_spec, caption, label, star=star, resize=resize, source=source)


def _split(segment: str) -> tuple[str, str | None]:
    base, _, sev = segment.partition("/")
    return base, (sev or None)


def corruption_table(
    df: pd.DataFrame, rows: Sequence[tuple[str, Sequence[tuple[str, str]]]], families: dict[str, Sequence[str]], *,
    value: str = "accuracy", caption: str, label: str, std: bool = True, decimals: int = 1, pct: bool = True,
    star: bool = True, source: str = "",
) -> str:
    """Per-corruption table in the ImageNet-C paper's layout: columns grouped by family, a trailing Avg.

    df    tidy rows with columns segment ("fog/s5" or "fog"), series, seed and `value`.
    rows  [(group label, [(series key, display label), ...]), ...], e.g.
          [("Models", [("large", "ViT-B/16"), ("small", "ResNet-50")]), ("Gates", [("fixed", "Fixed TS"), ...])]
    families  {"noise": [...], "blur": [...], ...} in column order (GlobalConfig.corruption_families); only
          corruptions present in df get a column, and a family with none is dropped.
    """
    df = df.copy()
    df["_base"] = df["segment"].map(lambda s: _split(s)[0])
    present = set(df["_base"])
    columns = [(fam, c) for fam, cs in families.items() for c in cs if c in present]
    extra = sorted(present - {c for _, c in columns})
    if extra:
        columns += [("other", c) for c in extra]
    fam_order = list(dict.fromkeys(f for f, _ in columns))
    seeds = sorted(df["seed"].unique())

    def per_seed_values(series: str) -> pd.DataFrame:     # (seed x corruption) of `value`
        d = df[df["series"] == series].groupby(["seed", "_base"])[value].mean().unstack("_base")
        return d.reindex(index=seeds, columns=[c for _, c in columns])

    body_rows, group_sizes = [], []
    for group, members in rows:
        group_sizes.append(len(members))
        for key, name in members:
            v = per_seed_values(key)
            avg = v.mean(axis=1, skipna=True)                # Avg. is taken per seed, then summarised over seeds
            cells = []
            for c in v.columns:
                col = v[c].dropna()
                cells.append(fmt_cell(col.mean() if len(col) else float("nan"),
                                      col.std(ddof=1) if std and len(col) > 1 else None, decimals, pct))
            avg_ok = avg.dropna()
            cells.append(fmt_cell(avg_ok.mean() if len(avg_ok) else float("nan"),
                                  avg_ok.std(ddof=1) if std and len(avg_ok) > 1 else None, decimals, pct))
            body_rows.append((group, name, cells))

    n_cols = len(columns)
    spec = "ll|" + "|".join("c" * sum(1 for f, _ in columns if f == fam) for fam in fam_order) + "|c"
    cursor, cmid, fam_cells = 3, [], []
    for fam in fam_order:
        n = sum(1 for f, _ in columns if f == fam)
        fam_cells.append(f"\\multicolumn{{{n}}}{{c}}{{{latex_escape(fam.capitalize())}}}")
        cmid.append(f"\\cmidrule(lr){{{cursor}-{cursor + n - 1}}}")
        cursor += n
    body = ["& & " + " & ".join(fam_cells) + " & \\\\", "".join(cmid),
            "Group & Method & " + " & ".join(latex_escape(ABBREV.get(c, c)) for _, c in columns) + " & Avg. \\\\",
            "\\midrule"]
    i = 0
    for gi, (group, members) in enumerate(rows):
        for j in range(len(members)):
            g_cell = f"\\multirow{{{len(members)}}}{{*}}{{\\textit{{{latex_escape(group)}}}}}" if j == 0 else ""
            _, name, cells = body_rows[i]
            body.append(f"{g_cell} & {latex_escape(name)} & " + " & ".join(cells) + " \\\\")
            i += 1
        if gi < len(rows) - 1:
            body.append("\\midrule")
    del n_cols
    return table_env(body, spec, caption, label, star=star, source=source)


def write_table(path: str | Path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"wrote {path}")
    return path


if __name__ == "__main__":
    import shutil
    import subprocess
    import tempfile

    assert fmt_cell(0.5134) == "51.3" and fmt_cell(0.5134, 0.0041) == "51.3 {\\scriptsize$\\pm$0.4}"
    assert fmt_cell(float("nan")) == "--" and fmt_cell(0.5, float("nan")) == "50.0" and fmt_cell(0.1234, pct=False, decimals=3) == "0.123"
    assert latex_escape("a_b & 50%") == r"a\_b \& 50\%"

    fam = {"noise": ["gaussian_noise", "shot_noise"], "weather": ["fog", "snow"], "digital": ["contrast"]}
    rng = np.random.RandomState(0)
    recs = []
    for seed in (0, 1, 2):
        for seg in ("snow/s5", "fog/s5", "gaussian_noise/s5", "contrast/s5"):   # deliberately NOT in header order
            for series, base in (("large", 0.40), ("small", 0.35), ("ours", 0.55)):
                recs.append({"seed": seed, "segment": seg, "series": series,
                             "accuracy": base + 0.1 * (seg.startswith("fog")) + 0.01 * rng.randn()})
    df = pd.DataFrame(recs)
    df.loc[(df.series == "small") & (df.segment == "snow/s5"), "accuracy"] = np.nan   # a missing cell
    rows = [("Models", [("large", "ViT-B/16"), ("small", "ResNet-50")]), ("Gates", [("ours", "Ours (nuclear_norm)")])]
    tex = corruption_table(df, rows, fam, caption="Accuracy (\\%).", label="tab:test")

    header = next(l.strip() for l in tex.splitlines() if l.strip().startswith("Group &"))
    cols = [c.strip() for c in header.split("&")[2:-1]]
    assert cols == ["Gauss.", "Fog", "Snow", "Contrast"], cols                    # family order, not input order
    large = next(l for l in tex.splitlines() if "ViT-B/16" in l).split("&")
    assert large[2].strip().startswith("40."), "Gauss. column must hold gaussian_noise"
    assert "pm" in large[3] and "50." in large[3], "Fog column holds fog (0.5)"
    small = next(l for l in tex.splitlines() if "ResNet-50" in l).split("&")
    assert small[4].strip() == "--", "a missing cell prints --, it does not shift the others"
    assert "\\multirow{2}{*}{\\textit{Models}}" in tex and "\\multirow{1}{*}{\\textit{Gates}}" in tex
    # only gaussian_noise is in the data, so Noise is 1 column wide; a family with no data would be dropped
    assert "\\multicolumn{1}{c}{Noise}" in tex and "\\multicolumn{2}{c}{Weather}" in tex and "\\multicolumn{1}{c}{Digital}" in tex
    avg_ours = next(l for l in tex.splitlines() if "Ours" in l).rstrip(" \\").split("&")[-1].strip()
    assert avg_ours.startswith("5") and "pm" in avg_ours

    plain = latex_table(["Gate input", "Avg.", "Order"], [["Fixed TS", "46.7", "n/a"], ["Ours", "51.3", "0.71"]],
                        caption="Proxies.", label="tab:proxies", midrule_before=[1], star=False)
    assert plain.count("\\midrule") == 2 and "\\begin{table}[t]" in plain and "Gate input & Avg. & Order" in plain

    if shutil.which("pdflatex"):
        doc = ("\\documentclass{article}\\usepackage{booktabs,multirow,graphicx}\\usepackage[landscape]{geometry}"
               "\\begin{document}\n" + tex + "\n" + plain + "\\end{document}\n")
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "t.tex").write_text(doc.replace("table*", "table"))
            r = subprocess.run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "t.tex"], cwd=tmp,
                               capture_output=True, text=True, timeout=120)
            assert r.returncode == 0 and (Path(tmp) / "t.pdf").exists(), r.stdout[-1500:]
        print("tables: generated LaTeX compiles with pdflatex")
    print("tables self-test passed")
